import type { Phase, Skill, SkillGroup, SkillsData } from '../src/data/skills-data';
import {
  LEAD_SKILL_BY_COMMAND,
  PHASE_META,
  PHASE_ORDER,
  SKILL_PHASE_MAP,
} from './skills-phase-map';

export interface ParsedFrontmatter {
  name: string;
  description: string;
  raw: Record<string, string>;
}

export interface SkillFrontmatter {
  slug: string;
  name: string;
  description: string;
  phase: Phase;
  triggers: string[];
  related: string[];
}

export function parseFrontmatter(content: string): ParsedFrontmatter | null {
  const match = content.match(/^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*\r?\n/);
  if (!match) {
    return null;
  }

  const raw: Record<string, string> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) {
      continue;
    }

    const key = line.slice(0, colonIdx).trim();
    const value = line
      .slice(colonIdx + 1)
      .trim()
      .replace(/^['"]|['"]$/g, '');
    if (key) {
      raw[key] = value;
    }
  }

  if (!raw.name || !raw.description) {
    return null;
  }

  return {
    name: raw.name,
    description: raw.description,
    raw,
  };
}

export function extractBody(content: string): string {
  const match = content.match(/^---[ \t]*\r?\n[\s\S]*?\r?\n---[ \t]*\r?\n([\s\S]*)$/);
  return match?.[1]?.trimStart() ?? content;
}

export function normalizeSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const SKILL_REF_PATTERNS = [
  /\buse the `([a-z][a-z0-9-]+[a-z0-9])` skill/g,
  /\bfollow the `([a-z][a-z0-9-]+[a-z0-9])` skill/gi,
  /\binvoke the `([a-z][a-z0-9-]+[a-z0-9])` skill/g,
  /\bcontinue with `([a-z][a-z0-9-]+[a-z0-9])`/g,
  /\buse `([a-z][a-z0-9-]+[a-z0-9])` skill/g,
  /`([a-z][a-z0-9-]+[a-z0-9])` skill\b/g,
  /`([a-z][a-z0-9-]+[a-z0-9])` persona\b/g,
  /\bsee `([a-z][a-z0-9-]+[a-z0-9])`/gi,
  /──→ ([a-z][a-z0-9-]+[a-z0-9])\b/g,
  /→ `([a-z][a-z0-9-]+[a-z0-9])`/g,
];

export function resolveRelatedSkills(
  content: string,
  knownSlugs: Set<string>,
  slug: string,
): string[] {
  const refs = new Set<string>();

  for (const pattern of SKILL_REF_PATTERNS) {
    pattern.lastIndex = 0;
    let match: RegExpExecArray | null = pattern.exec(content);
    while (match !== null) {
      refs.add(match[1]);
      match = pattern.exec(content);
    }
  }

  return [...refs]
    .filter((ref) => ref !== slug && knownSlugs.has(ref))
    .sort((a, b) => a.localeCompare(b));
}

export function classifyPhase(slug: string): Phase {
  const phase = SKILL_PHASE_MAP[slug];
  if (!phase) {
    throw new Error(`No phase mapping for skill slug: ${slug}`);
  }

  return phase;
}

export function buildTriggers(slug: string, phase: Phase, command: string): string[] {
  if (phase === 'meta' || !command) {
    return [];
  }

  const leadSlug = LEAD_SKILL_BY_COMMAND[command];
  if (leadSlug === slug) {
    return [command];
  }

  return [];
}

export function formatSkillMarkdown(frontmatter: SkillFrontmatter, body: string): string {
  const lines = [
    '---',
    `slug: ${frontmatter.slug}`,
    `name: ${JSON.stringify(frontmatter.name)}`,
    `description: ${JSON.stringify(frontmatter.description)}`,
    `phase: ${frontmatter.phase}`,
    `triggers: ${JSON.stringify(frontmatter.triggers)}`,
    `related: ${JSON.stringify(frontmatter.related)}`,
    '---',
    '',
    body.trimEnd(),
    '',
  ];

  return lines.join('\n');
}

export function buildSkillRecord(
  slug: string,
  parsed: ParsedFrontmatter,
  bodyContent: string,
  knownSlugs: Set<string>,
): Skill {
  const phase = classifyPhase(slug);
  const command = PHASE_META[phase].command;

  return {
    slug,
    name: parsed.name,
    description: parsed.description,
    phase,
    triggers: buildTriggers(slug, phase, command),
    related: resolveRelatedSkills(bodyContent, knownSlugs, slug),
  };
}

export function groupSkills(skills: Skill[]): SkillGroup[] {
  const byPhase = new Map<Phase, Skill[]>();

  for (const phase of PHASE_ORDER) {
    byPhase.set(phase, []);
  }

  for (const skill of skills) {
    byPhase.get(skill.phase)?.push(skill);
  }

  return PHASE_ORDER.map((phase) => {
    const meta = PHASE_META[phase];
    const phaseSkills = [...(byPhase.get(phase) ?? [])].sort((a, b) =>
      a.name.localeCompare(b.name),
    );

    return {
      phase,
      label: meta.label,
      command: meta.command,
      skills: phaseSkills,
    };
  });
}

export function buildSkillsData(skills: Skill[]): SkillsData {
  return {
    groups: groupSkills(skills),
    skills: [...skills].sort((a, b) => a.slug.localeCompare(b.slug)),
  };
}

export function generateSkillsDataSource(data: SkillsData): string {
  return `// Generated by scripts/sync-skills.ts — do not edit by hand.
export type Phase =
  | 'meta'
  | 'define'
  | 'plan'
  | 'build'
  | 'test'
  | 'review'
  | 'simplify'
  | 'ship';

export interface Skill {
  slug: string;
  name: string;
  description: string;
  phase: Phase;
  triggers: string[];
  related: string[];
}

export interface SkillGroup {
  phase: Phase;
  label: string;
  command: string;
  skills: Skill[];
}

export interface SkillsData {
  groups: SkillGroup[];
  skills: Skill[];
}

export const skillsData = ${JSON.stringify(data, null, 2)} as const satisfies SkillsData;
`;
}
